/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yang_www_utils_AppUtils */

#ifndef _Included_com_yang_www_utils_AppUtils
#define _Included_com_yang_www_utils_AppUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yang_www_utils_AppUtils
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yang_www_utils_AppUtils_getStringFromJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
